name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install gemfile
        run: cd awm-api && bundle install
      - name: Rubocop
        run: cd awm-api && bundle exec rubocop
      - name: Rails Best Practices
        run:
          cd awm-api && bundle exec rails_best_practices -e
          "db/schema.rb,db/migrate,vendor,app/models/application_record.rb"
      - name: Rpec
        run: cd awm-api && bundle exec rspec --format documentation
      - name: reek
        run: cd awm-api && bundle exec reek
